import 'dart:ui' as ui;
import 'package:flutter/widgets.dart';
import 'noise_generator.dart';
import 'neumorphic_shape_painter.dart';

/// A custom painter that creates a frosted glass effect with a neumorphic design.
///
/// The [NeumorphicFrostGlassSurfacePainter] class extends a base painter and
/// customizes the painting to achieve a frosted glass appearance with a
/// neumorphic style. This painter can be used to create visually appealing
/// surfaces in a Flutter application.
///
/// The [shape] parameter is inherited from the base class and can be used to
/// define the shape of the painted surface. The [strokeWidth] is set to 0
/// by default to create a smooth, filled surface without any stroke.
/// This painter extends the [NeumorphicShapePainter] to provide a unique
/// visual style that combines the frosted glass effect with neumorphic
/// design principles.
///
/// The frosted glass effect is achieved by applying a blur and a semi-transparent
/// overlay to the painted surface, giving it a frosted appearance. The neumorphic
/// design adds depth and a soft, embossed look to the surface.
///
/// This painter can be used to create visually appealing UI elements that
/// stand out with a modern and elegant look.
class NeumorphicFrostGlassSurfacePainter extends NeumorphicShapePainter {
  /// A cached small noise texture image used for rendering.
  ///
  /// This image is generated by the `NoiseGenerator` and is used to add a frosted glass effect
  /// to the Neumorphic UI elements.
  final ui.Image noiseTexture = NoiseGenerator.cachedSmall;

  /// Creates a [NeumorphicFrostGlassSurfacePainter] with the given shape.
  NeumorphicFrostGlassSurfacePainter({super.shape}) : super(strokeWidth: 0);

  /// Paints a frosted glass surface on the given canvas with the specified blur
  /// effect.
  ///
  /// The [canvas] parameter is the canvas on which the frosted glass surface
  /// will be painted.
  ///
  /// The [sigmaX] parameter controls the horizontal blur intensity. The default
  /// value is 0.9.
  ///
  /// The [sigmaY] parameter controls the vertical blur intensity. The default
  /// value is 0.9.
  void paintSurface(Canvas canvas, {double sigmaX = 0.9, double sigmaY = 0.9}) {
    final paint = Paint()
      ..imageFilter = ui.ImageFilter.blur(
          sigmaX: sigmaX, sigmaY: sigmaY, tileMode: TileMode.repeated)
      ..shader = ImageShader(
        noiseTexture,
        TileMode.repeated,
        TileMode.repeated,
        Matrix4.identity().storage,
      );

    canvas.save();
    canvas.clipPath(innerPath);
    canvas.drawPath(innerPath, paint);
    canvas.restore();
  }
}
